<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Movie Favorites</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        body {
            padding-top: 70px;
        }
    </style>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">My Favorites Movies</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form id="search-form" class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" id="search-title" name="search-title" placeholder="Frozen" class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Search Movie</button>
            </form>
        </div><!--/.navbar-collapse -->
    </div>
</nav>



<div class="container" id="search-results-wrapper">

</div>


<!-- Page Content -->
<div class="container">


    <?php foreach ($favorites  as $favorite) { ?>
        <?php extract($favorite); ?>
        <div class="row">
            <div class="col-md-3">
                <img src="<?= $Poster ?>" class="img-responsive img-rounded" alt="<?= $Title ?>">
            </div>
            <div class="col-md-9">
                <h2><?= $Title ?></h2>
                <h3><?= $Year ?>, <?= $Genre ?></h3>
                <strong><?= $Director ?></strong>
                <p><?= $Actors ?></p>
                <p><?= $Plot ?></p>
            </div>
        </div>
        <hr>



<!--        "-->
<!--        [Title] => The Martian-->
<!--        [Year] => 2015-->
<!--        [Rated] => PG-13-->
<!--        [Released] => 02 Oct 2015-->
<!--        [Runtime] => 144 min-->
<!--        [Genre] => Adventure, Drama, Sci-Fi-->
<!--        [Director] => Ridley Scott-->
<!--        [Writer] => Drew Goddard (screenplay), Andy Weir (book)-->
<!--        [Actors] => Matt Damon, Jessica Chastain, Kristen Wiig, Jeff Daniels-->
<!--        [Plot] => An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive.-->
<!--        [Language] => English, Mandarin-->
<!--        [Country] => USA, UK-->
<!--        [Awards] => Nominated for 7 Oscars. Another 34 wins & 171 nominations.-->
<!--        [Poster] => https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg-->
<!--        [Metascore] => 80-->
<!--        [imdbRating] => 8.0-->
<!--        [imdbVotes] => 495,332-->
<!--        [imdbID] => tt3659388-->
<!--        [Type] => movie-->
<!--        [Response] => True-->
<!--        )-->
<!--        "-->
    <?php } ?>

</div>






<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>

    $(document).ready(function(){

        $("#search-form").on("submit", function(e){
            e.preventDefault();
            e.stopPropagation();

            $.getJSON("api/search/"+ $("#search-title").val(), function(data){

                var _html = [
                    "<div class='row'>"
                ];

                $.each(data.Search, function(movie){
                    console.log(movie)
                    var _movie_html = [
                        "<div class='col-md-4'>",
                            "<div class='row'>",
                                "<div class='col-md-6'>",
                                    "<img src='"+ this.Poster +"' class='img-responsive img-rounded' alt='"+ this.Title +"'>",
                                "</div>",
                                "<div class='col-md-6'>",
                                    "<h4>"+ this.Title +"</h4>",
                                    "<h5>"+ this.Year +"</h5>",
                                    '<button data-imdbid="'+ this.imdbID +'" type="button" class="add-favorite btn btn-success btn-sm">Add to Favorites</button>',
                                "</div>",
                            "</div>",
                        "</div>"
                    ];
                    _html.push(_movie_html.join(""));
                });

                _html.push("</div> ");

                $("#search-results-wrapper").html(_html.join(""));


                $(".add-favorite").on("click", function(){
                    var id = $(this).data("imdbid");
                    $.ajax({
                            method: "POST",
                            url: "api/favorites/",
                            dataType: "json",
                            data: { imdbID: id }
                        })
                        .done(function( msg ) {
                            location.reload();
                        });
                });

            });

        });


    });

</script>


</body>
</html>